### ISSUE TITLE
Extend support to manage password policies Aria product components

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#111]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Extend the module to support managing password policies for these components' expiration, policy, and lockout for on-premises Aria product components in "vcf-mode".

### Use Case(s)

**Today,** if a user deploys one of the supported on-premises Aria products in "vcf-mode",  most passwords can be rotated/remediated for Aria components using SDDC Manager. This would extend the module to support managing policies for expiration, policy, and lockout for these components.

### Potential Configuration

To be determined.

**Comment by burnsjared0415** [comment]
i can pick this up if no one has it
