### ISSUE TITLE
Error: NSX Edge password policy not returned when invoking the auth-policy function

### ISSUE THREAD

**Issue by SecurityCarlosPhoenix** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#136]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### PowerVCF

2.4.0

### VMware Cloud Foundation

5.x

### PowerShell

PowerShell 7

### Guest Operating System

Linux

### Description

NSX Edge password policy was not returned when invoking the auth-policy function.

### Expected Behavior

Return password authentication policy.

### Actual Behavior

`nsxEdgeRootPass` not accepted in order to authenticate and run the password authentication policy.

### Steps to Reproduce

`Request-NsxtEdgePasswordComplexity` cmdlet.

### Screenshots

<img width="1849" alt="Power Shell running code for Password Policy__with NSX Edge not working" src="https://github.com/vmware/powershell-module-for-vmware-cloud-foundation/assets/149444803/2635b8e9-8e26-4785-97b6-c1a8f5cf00b2">

### Additional Context

Used lab from peer Colin Smith (VCF 5, fresh install, defaults).

**Comment by tenthirtyam** [comment]
@sowjuec - could you see if you can reproduce this issue from Carlos?

**Comment by sowjuec** [comment]
Hi, 
This issue could not be reproduced. I tried the cmdlet on VCF5.1 environment on both powershell5 and powershell7 versions. The nsxEdgeRootPass is a variable which holds root password and is being read directly from SDDC manager. 
$nsxEdgeRootPass = (Get-VCFCredential ********

By any chance is your Edge VM belongs to isolated domain?

If that is case only we will not be able to read the credential for the same and we may have issues there. could you please confirm.

**Comment by garlicNova** [comment]
Follow up with Carlos, the environment has 2 edge cluster nodes, with the 2nd one being deployed from NSX manager instead of SDDC Manager.  the script hits this issue where the authentication information is not stored with SDDC Manager.  
we can enhance the module to ask for password or to take in individual node details as extra parameter arguments

**Comment by tenthirtyam** [comment]
Updating this to an `enhancement` based on https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/issues/136#issuecomment-1787834744 and moving to the v1.7.0 milestone.

Assigning to @garlicNova.

**Comment by garlicNova** [comment]
enhancement request 
1. better error handling.  if nsx edge node is not found in the sddc manager database return an error instead it falls into try/catch phrase 
2. Add an option to the cmd to pass in individual edge node FQDN/user/password to allow the cmdlet to pull policy either through sddc manager database or through individual edge node.

**Comment by tenthirtyam** [comment]
@burnsjared0415 - could you pick this one up?

**Comment by burnsjared0415** [comment]
Working on Error handling, there is a default error if the Edge does not exist.
 Invoke-VMScript : 11/20/2023 9:22:54 AM	Invoke-VMScript		Could not find VirtualMachine with name 

We can update this to be in catch 

Function Request-NsxtEdgePasswordComplexity {
    <#
		.SYNOPSIS
		Retrieves the password complexity policy for NSX Edge nodes.=.

        .DESCRIPTION
        The Request-NsxtEdgePasswordComplexity cmdlet retrieves the password complexity policy for each NSX Edge
        node for a workload domain. The cmdlet connects to the SDDC Manager using the -server, -user, and -pass values:
        - Validates that network connectivity and authentication is possible to SDDC Manager
        - Validates that network connectivity and authentication is possible to NSX Local Manager
		- Retrieves the password complexity policy

        .EXAMPLE
        Request-NsxtEdgePasswordComplexity -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re1! -domain sfo-m01
        This example retrieves the password complexity policy for each NSX Edge node for a workload domain

        .EXAMPLE
        Request-NsxtEdgePasswordComplexity -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re1! -domain sfo-m01 -drift -reportPath "F:\Reporting" -policyFile "passwordPolicyConfig.json"
        This example retrieves the password complexity policy for each NSX Edge node for a workload domain and checks the configuration drift using the provided configuration JSON.

        .EXAMPLE
        Request-NsxtEdgePasswordComplexity -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re1! -domain sfo-m01
        This example retrieves the password complexity policy for each NSX Edge node for a workload domain and compares the configuration against the product defaults.

        .PARAMETER server
        The fully qualified domain name of the SDDC Manager instance.

        .PARAMETER user
        The username to authenticate to the SDDC Manager instance.

        .PARAMETER pass
        The password to authenticate to the SDDC Manager instance.

        .PARAMETER domain
        The name of the workload domain to retrieve the policy from.

        .PARAMETER drift
        Switch to compare the current configuration against the product defaults or a JSON file.

        .PARAMETER reportPath
        The path to save the policy report.

        .PARAMETER policyFile
        The path to the policy configuration file.
    #>

    Param (
        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$server,
        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$user,
        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$pass,
        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$domain,
        [Parameter (Mandatory = $false, ParameterSetName = 'drift')] [ValidateNotNullOrEmpty()] [Switch]$drift,
        [Parameter (Mandatory = $false)] [ValidateNotNullOrEmpty()] [String]$reportPath,
        [Parameter (Mandatory = $false)] [ValidateNotNullOrEmpty()] [String]$policyFile,
        [Parameter (Mandatory = $false)] [ValidateNotNullOrEmpty()] [String]$singleEdgeNode,
        [Parameter (Mandatory = $false)] [ValidateNotNullOrEmpty()] [String]$singleEdgeNodepass
	)
    
	Try {
        if (Test-VCFConnection -server $server) {
            if (Test-VCFAuthentication -server $server -user $user -pass $pass) {
                if ($drift) {
                    $version = Get-VCFManager -version
                    if ($PsBoundParameters.ContainsKey('policyFile')) {
                        $requiredConfig = (Get-PasswordPolicyConfig -version $version -reportPath $reportPath -policyFile $policyFile ).nsxEdge.passwordComplexity
                    } else {
                        $requiredConfig = (Get-PasswordPolicyConfig -version $version).nsxEdge.passwordComplexity
                    }
                }
                if (Get-VCFWorkloadDomain | Where-Object { $_.name -eq $domain }) {
                    if (($vcfVcenterDetails = Get-vCenterServerDetail -server $server -user $user -pass $pass -domain $domain)) {
                        if (Test-vSphereConnection -server $($vcfVcenterDetails.fqdn)) {
                            if (Test-vSphereAuthentication -server $vcfVcenterDetails.fqdn -user $vcfVcenterDetails.ssoAdmin -pass $vcfVcenterDetails.ssoAdminPass) {
                                if (($vcfNsxDetails = Get-NsxtServerDetail -fqdn $server -username $user -password $pass -domain $domain -listNodes)) {
                                    if (Test-NSXTConnection -server $vcfNsxDetails.fqdn) {
                                        if (Test-NSXTAuthentication -server $vcfNsxDetails.fqdn -user $vcfNsxDetails.adminUser -pass $vcfNsxDetails.adminPass) {
                                            $nsxtPasswordComplexityPolicy = New-Object System.Collections.ArrayList
                                            $nsxtEdgeNodes = (Get-NsxtEdgeCluster | Where-Object {$_.member_node_type -eq "EDGE_NODE"})
                                               if([string]::IsNullOrEmpty($singleEdgeNode)){
                                                    foreach ($nsxtEdgeNode in $nsxtEdgeNodes.members) {
                                                    $nsxEdgeRootPass = (Get-VCFCredential | Where-Object {$_.resource.resourceName -eq ($nsxtEdgeNode.display_name + '.' + $vcfNsxDetails.fqdn.Split('.',2)[-1]) -and $_.username -eq "root"}).password
                                                     if ($nsxtEdgeNodePolicy = Get-LocalPasswordComplexity -vmName $($nsxtEdgeNode.display_name) -guestUser root -guestPassword $nsxEdgeRootPass -nsx ) {
                                                         $NsxtEdgePasswordComplexityObject = New-Object -TypeName psobject
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Workload Domain" -notepropertyvalue $domain
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "System" -notepropertyvalue $nsxtEdgeNode.display_name
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Length" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Length' -ne $requiredConfig.minLength) { "$($nsxtEdgeNodePolicy.'Min Length') [ $($requiredConfig.minLength) ]" } else { "$($nsxtEdgeNodePolicy.'Min Length')" }} else { "$($nsxtEdgeNodePolicy.'Min Length')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Lowercase" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Lowercase' -ne $requiredConfig.minLowercase) { "$($nsxtEdgeNodePolicy.'Min Lowercase') [ $($requiredConfig.minLowercase) ]" } else { "$($nsxtEdgeNodePolicy.'Min Lowercase')" }} else { "$($nsxtEdgeNodePolicy.'Min Lowercase')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Uppercase" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Uppercase' -ne $requiredConfig.minUppercase) { "$($nsxtEdgeNodePolicy.'Min Uppercase') [ $($requiredConfig.minUppercase) ]" } else { "$($nsxtEdgeNodePolicy.'Min Uppercase')" }} else { "$($nsxtEdgeNodePolicy.'Min Uppercase')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Numerical" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Numerical' -ne $requiredConfig.minNumerical) { "$($nsxtEdgeNodePolicy.'Min Numerical') [ $($requiredConfig.minNumerical) ]" } else { "$($nsxtEdgeNodePolicy.'Min Numerical')" }} else { "$($nsxtEdgeNodePolicy.'Min Numerical')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Special" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Special' -ne $requiredConfig.minSpecial) { "$($nsxtEdgeNodePolicy.'Min Special') [ $($requiredConfig.minSpecial) ]" } else { "$($nsxtEdgeNodePolicy.'Min Special')" }} else { "$($nsxtEdgeNodePolicy.'Min Special')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Unique" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Unique' -ne $requiredConfig.minUnique) { "$($nsxtEdgeNodePolicy.'Min Unique') [ $($requiredConfig.minUnique) ]" } else { "$($nsxtEdgeNodePolicy.'Min Unique')" }} else { "$($nsxtEdgeNodePolicy.'Min Unique')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Max Retries" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Max Retries' -ne $requiredConfig.retries) { "$($nsxtEdgeNodePolicy.'Max Retries') [ $($requiredConfig.retries) ]" } else { "$($nsxtEdgeNodePolicy.'Max Retries')" }} else { "$($nsxtEdgeNodePolicy.'Max Retries')" })
                                                         $nsxtPasswordComplexityPolicy += $NsxtEdgePasswordComplexityObject
                                                    } else {
                                                       Write-Error "Unable to retrieve Password Complexity Policy from NSX Edge node ($($nsxtEdgeNode.display_name)): PRE_VALIDATION_FAILED"
                                                      }
                                                    }
                                                 }elseif($singleEdgeNode -ne $null){
                                                   if ($nsxtEdgeNodePolicy = Get-LocalPasswordComplexity -vmName $($singleEdgeNode) -guestUser root -guestPassword $singleEdgeNodepass -nsx ) {
                                                         $NsxtEdgePasswordComplexityObject = New-Object -TypeName psobject
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Workload Domain" -notepropertyvalue $domain
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "System" -notepropertyvalue $singleEdgeNode
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Length" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Length' -ne $requiredConfig.minLength) { "$($nsxtEdgeNodePolicy.'Min Length') [ $($requiredConfig.minLength) ]" } else { "$($nsxtEdgeNodePolicy.'Min Length')" }} else { "$($nsxtEdgeNodePolicy.'Min Length')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Lowercase" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Lowercase' -ne $requiredConfig.minLowercase) { "$($nsxtEdgeNodePolicy.'Min Lowercase') [ $($requiredConfig.minLowercase) ]" } else { "$($nsxtEdgeNodePolicy.'Min Lowercase')" }} else { "$($nsxtEdgeNodePolicy.'Min Lowercase')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Uppercase" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Uppercase' -ne $requiredConfig.minUppercase) { "$($nsxtEdgeNodePolicy.'Min Uppercase') [ $($requiredConfig.minUppercase) ]" } else { "$($nsxtEdgeNodePolicy.'Min Uppercase')" }} else { "$($nsxtEdgeNodePolicy.'Min Uppercase')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Numerical" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Numerical' -ne $requiredConfig.minNumerical) { "$($nsxtEdgeNodePolicy.'Min Numerical') [ $($requiredConfig.minNumerical) ]" } else { "$($nsxtEdgeNodePolicy.'Min Numerical')" }} else { "$($nsxtEdgeNodePolicy.'Min Numerical')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Special" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Special' -ne $requiredConfig.minSpecial) { "$($nsxtEdgeNodePolicy.'Min Special') [ $($requiredConfig.minSpecial) ]" } else { "$($nsxtEdgeNodePolicy.'Min Special')" }} else { "$($nsxtEdgeNodePolicy.'Min Special')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Min Unique" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Min Unique' -ne $requiredConfig.minUnique) { "$($nsxtEdgeNodePolicy.'Min Unique') [ $($requiredConfig.minUnique) ]" } else { "$($nsxtEdgeNodePolicy.'Min Unique')" }} else { "$($nsxtEdgeNodePolicy.'Min Unique')" })
                                                         $NsxtEdgePasswordComplexityObject | Add-Member -notepropertyname "Max Retries" -notepropertyvalue $(if ($drift) { if ($nsxtEdgeNodePolicy.'Max Retries' -ne $requiredConfig.retries) { "$($nsxtEdgeNodePolicy.'Max Retries') [ $($requiredConfig.retries) ]" } else { "$($nsxtEdgeNodePolicy.'Max Retries')" }} else { "$($nsxtEdgeNodePolicy.'Max Retries')" })
                                                         $nsxtPasswordComplexityPolicy += $NsxtEdgePasswordComplexityObject
                                                    }
                                                  }
                                         
                                        }
                                    }
                                    return $nsxtPasswordComplexityPolicy
                                }
                            }
                        }
                    }
                } else {
                    Write-Error "Unable to find Workload Domain named ($domain) in the inventory of SDDC Manager ($server): PRE_VALIDATION_FAILED"
                }
            }
        }
	} Catch {
        Debug-ExceptionWriter -object $_
    } Finally {
        if ($global:DefaultVIServers) {
            Disconnect-VIServer -Server $global:DefaultVIServers -Confirm:$false
        }
    }
}

$server = "sf0-sddc.rainpole.io"
$user = "administrator@vsphere.local"
$pass = "VMw@re1!"
$domain = "sfo-m01"
$node = "sfomgtedg01"
$singleEdgeNodepass = "VMw@re1!VMw@re1!"


Request-NsxtEdgePasswordComplexity -server $server -user $user -pass $pass -domain $domain -singleEdgeNode $node -singleEdgeNodepass $singleEdgeNodepass

**Comment by tenthirtyam** [comment]
Addressed in #148.
