### ISSUE TITLE
Missing account lockout data for SDDC Manager and vCenter Server on HTML report

### ISSUE THREAD

**Issue by bhumitra** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#152]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### PowerShell Version

7.2

### PowerCLI Version

13.1

### Module Version

1.7

### PowerValidatedSolutions Version

1.8

### PowerVCF Version

2.7

### Guest Operating System

Windows Server 2019

### Description

I ran the `Invoke-PasswordPolicyManager` cmdlet and the report is missing data for account lockout polices. See screenshots 
Problem with the below items- 

- SDDC Manager - Account Lockout
- vCenter Server - Account Lockout (Local Users)

The file where lockout policy resides has changed in VCF 5.1 and above. This change is due to photon OS being upgraded from version 3.0 to 4.0.

The file has changed from /etc/pam.d/system-password to /etc/security/faillock.conf

This change impacts the appliances which were upgraded from Photon OS 3.0 to 4.0 in VCF 5.1 release.
i.e. SDDC manager and vCenter server

The individual cmdlets are also returning just the host name, e.g. 

PS C:\> Request-VcenterAccountLockout -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass ****** -domain sfo-m01

System
------
sfo-m01-vc01

We should also enhance the above cmdlet to show "N/A" as values for parameter which are configurable but not set.
e.g. in the above command, we could return Max Failures, Unlock Interval (sec), and Root Unlock Interval (sec) with value as N/A as it is not set in the report and in the command. 

![Screenshot 2024-01-24 at 9 26 20 AM](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/8632869/45b92ede-ab79-4e37-943b-bfdcaeaed2ac)

### Error or Debug Output

See screenshots 

### Expected Behavior

Should return the policy data. 

### Actual Behavior

See desc. 

### Steps to Reproduce

See desc.

**Comment by sowjuec** [comment]
Hi Bhumitra, This I observed today with ' Request-SDDCManagerPasswordComplexity' cmdlet. This was because the system file '/etc/pam.d/system-password' is not containing any data except history on a fresh setup. After I did update with all the required values and then called Reqeust cmdlet it worked. Attached is the snaphost for reference.
![Screenshot 2024-01-29 at 4 00 50 PM](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/110152712/d50b5c0e-03ce-4197-9014-8e041ace186e)
![Screenshot 2024-01-29 at 4 01 08 PM](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/110152712/b98a5126-89f5-419b-8b36-00c2a16af13c)
![Screenshot 2024-01-29 at 4 01 19 PM](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/110152712/f2f530b7-5510-424b-8619-0407668a0ff5)

**Comment by bhumitra** [comment]
@sowjuec the file where lockout policy resides has changed in VCF 5.1 and above. This change is due to photon OS being upgraded from version 3.0 to 4.0. 

The file has changed from `/etc/pam.d/system-password` to `/etc/security/faillock.conf`

This change impacts the appliances which were upgraded from Photon OS 3.0 to 4.0 in VCF 5.1 release.
i.e. SDDC manager and vCenter server

**Comment by sowjuec** [comment]
Ok. Thanks for the information Bhumitra, Will try to resolve.

**Comment by bhumitra** [comment]
After the fix

<img width="1204" alt="Screenshot 2024-02-06 at 4 12 04 PM" src="https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/8632869/45ae32eb-a896-4a44-a4a0-7e53903855cc">

<img width="1196" alt="Screenshot 2024-02-06 at 4 12 09 PM" src="https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/8632869/bfc27588-7f84-437b-a004-f3cb2d5a1fdd">

<img width="976" alt="Screenshot 2024-02-05 at 6 48 47 PM" src="https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/8632869/cb491d33-48cc-4684-a913-654977fabba8">
