### ISSUE TITLE
WSA Local User Password Policy does not match Update

### ISSUE THREAD

**Issue by burnsjared0415** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#180]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1.0.0

### PowerShell Version

Core Powershell 7.3.11

### PowerCLI Version

13.2.1.22851661

### Module Version

lastest

### PowerValidatedSolutions Version

lastest

### PowerVCF Version

lastet

### Guest Operating System

Mac

### Description

I am working on Clustered Aria Workspace one Update and Request scripts, I have noticed that in the policy file we are only check 3 values:
```powershell
    $wsaLocalPasswordComplexity | Add-Member -notepropertyname 'minLength' -notepropertyvalue "1"
    $wsaLocalPasswordComplexity | Add-Member -notepropertyname 'retries' -notepropertyvalue "3"
    $wsaLocalPasswordComplexity | Add-Member -notepropertyname 'history' -notepropertyvalue "5"
```

but in the `Update-WsaLocalUserPasswordComplexity` we are look to update:
```powershell
Set-LocalPasswordComplexity -vmName ($wsaFqdn.Split("."))[-0] -guestUser root -guestPassword $wsaRootPass -minLength $minLength -uppercase $minUppercase -lowercase $minLowercase -numerical $minNumerical -special $minSpecial -unique $minUnique -class $minClass -sequence $maxSequence -history $history -retry $maxRetry | Out-Null
```

need to know which settings are correct between the two scripts

### Error or Debug Output

None

### Expected Behavior

just reviewed the two functions : Function `Get-PasswordPolicyDefault` and `Function Update-WsaLocalUserPasswordComplexity` 

### Actual Behavior

no behavior just a difference in functions

### Steps to Reproduce

just review functions

**Comment by burnsjared0415** [comment]
this command does not match for the checks either
```
Set-WsaPasswordPolicy -minLen $minLength -minLower $minLowercase -minUpper $minUppercase -minDigit $minNumeric -minSpecial $minSpecial -history $history -maxConsecutiveIdenticalCharacters $maxIdenticalAdjacent -maxPreviousPasswordCharactersReused $maxPreviousCharacters -tempPasswordTtlInHrs (Get-WsaPasswordPolicy).tempPasswordTtl -passwordTtlInDays $currentMaxDays -notificationThresholdInDays $currentWarnDays -notificationIntervalInDays $currentReminderDays | Out-Null
```

**Comment by tenthirtyam** [comment]
The upstream change in `PowerValidatedSolutions` has been merged. This can addressed once the next release of `PowerValidatedSolutions` is shipped. Likely v2.11.1.
