### ISSUE TITLE
Update-AriaLocalUserPasswordComplexity link in references is broken- 404 error

### ISSUE THREAD

**Issue by colin-cs** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#189]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Module Version

VMware.CloudFoundation.PasswordManagement v1.8.0

### Motivation

In the "References" subsection, the link for details on "update-arialocaluserpasswordcomplexity" module (https://vmware.github.io/powershell-module-for-vmware-cloud-foundation-password-management/documentation/functions/Update-AriaLocalUserPasswordComplexity.md) does not work.  You receive a 404 error when you click on it.

<img width="1350" alt="Screenshot 2024-05-02 at 9 28 47 AM" src="https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/157423424/ce4566c2-8b43-44a5-b230-dfe22215eca1">

**Comment by tenthirtyam** [comment]
I've republished the docs and this issue is now resolved.

Please clear your cache. 😄
