### ISSUE TITLE
Parameters for Aria component functions

### ISSUE THREAD

**Issue by colin-cs** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#190]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Module Version

v1.8.0

### Motivation

The `Request-AriaLocalUserPasswordComplexity`, `Get-AriaLocalUserPasswordComplexity`, `Update-AriaLocalUserPasswordComplexity` cmdlets all include a `-product`  parameter to target the query to a specific Aria product, however there is no guidance what switch needs be used with the parameter to define the targeted product. 

You can infer from examples that `vra` is for Aria Automation and `vrni` is for Aria Ops for Network (`vrni` is documented as its own parameter).  

The documentation needs to provide the definitive list Aria products for the parameters. This can/will be confusing to the users of these cmdlets.  Especially since the existing switches use older discontinued abbreviations.

### Suggestion

Minimally, update documentation to include include definitive list of `-product` parameter switches that the cmdlet will accept.

Optimally, update the cmdlets to use more current switches that map to the Aria name conventions. This particular modifiication may not be practical for a variety of reasons at the moment.

**Comment by tenthirtyam** [comment]
Assigning to @sowjuec.

**Comment by tenthirtyam** [comment]
I've republished the docs and this issue is now resolved.

Please clear your cache. 😄
