### ISSUE TITLE
Documentation Initial Reference

### ISSUE THREAD

**Issue by colin-cs** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#191]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Module Version

VMware.CloudFoundation.PasswordManagement

### Motivation

The main reference page - https://vmware.github.io/powershell-module-for-vmware-cloud-foundation-password-management/documentation/ - currently states 
"The module provides coverage for the following components:

ESXi
vCenter Single Sign-On
vCenter Server
NSX Local Manager
NSX Edge
SDDC Manager
Workspace ONE Access (Standalone)"

This may prove confusing as a user can readily see that Aria components are included when they review the actual cmdlets in the left-hand navigation.

### Suggestion

Recommend updating the page to reflect the additional coverage for the Aria components

**Comment by tenthirtyam** [comment]
Assigning to @sowjuec.

**Comment by tenthirtyam** [comment]
I've republished the docs and this issue is now resolved.

Please clear your cache. 😄
