### ISSUE TITLE
SDDC Manager data missing if not configured on appliance

### ISSUE THREAD

**Issue by burnsjared0415** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#198]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

When you run the report, if no data is present it include but mention that there is no datainstead of a blank column. 

Example:

<img width="1177" alt="image" src="https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/61466028/daac24e7-dbbb-4179-a166-4c9605c8b95b">

### Use Case(s)

State that no setting are set for the item.

### Potential Configuration

N/A

**Comment by sowjuec** [comment]
Since PPM module is making use of the PVS cmdlets available for fetching the data, it is required to get it corrected at the base function. Will raise ticket there and get it fixed there to get it fixed here.

**Comment by tenthirtyam** [comment]
The upstream change in `PowerValidatedSolutions` has been merged. This can be merged once the next release of `PowerValidatedSolutions` is shipped. Likely v2.11.1.

**Comment by tenthirtyam** [comment]
Resolved with https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/pull/214.
