### ISSUE TITLE
`Request-SsoPasswordComplexity` method is reading from both domains, when only one is specified, creating duplicate entries in the output

### ISSUE THREAD

**Issue by sowjuec** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#20]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

v5.0

### PowerShell Version

Windows Powershell 5.1

### PowerCLI Version

v13.0.0

### Module Version

v1.0.0.1002

### PowerValidatedSolutions Version

v2.2.0

### PowerVCF Version

v2.2.0.1002

### Guest Operating System

Windows Server 2019

### Environment Details

It is a VCF 5.0 SSO domain setup.

### Description

`Request-Sso*` cmdlets  is used to read SSO related password policy for a given domain in the SSO domain list

But this cmdlet  is reading both domains when only workload or management is specified.

### Error or Debug Output

https://gist.github.com/sowjuec/c557074f3f1b700702b630b2e6006ef2

### Expected Behavior

The command should have read SSO password policy against only one domain.

### Actual Behavior

The command is updating all the domains which are part of the SSO domain though only one domain info is passed.

### Steps to Reproduce

Run the following cmdlet following [the documentation](https://docs.vmware.com/en/VMware-Cloud-Foundation/4.5/vcf-operations/GUID-22C6746A-6703-47E5-B17A-313EC959EC62.html).

```powershell
Request-SsoPasswordComplexity -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain <domain which is passed in the above step> --- provide management domain info

Request-SsoPasswordComplexity -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain <domain which is not passed in the above step> --- provide any workload domain  info
```

After running both steps, the output for the second one will have duplicate entries as shown in the screenshot shared.

### Screenshots

![image](https://user-images.githubusercontent.com/110152712/234254449-468a5432-3cb1-44cc-8012-51811d25dbac.png)

**Comment by tenthirtyam** [comment]
Updated the content formatting, links, and inclusive language.
