### ISSUE TITLE
Enhance for updated SDDC Manager `minlen` defaults

### ISSUE THREAD

**Issue by sowjuec** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#200]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

The minimum length of the password has been increased as follows.

- 5.2: 15 characters
- 5.1: 12 characters

### Use Case(s)

Support the updated minimum lengths.

### Potential Configuration

Update the default values in the `Get-PasswordPolicyDefault` function.

**Comment by tenthirtyam** [comment]
Resolved in #206
