### ISSUE TITLE
`Update-SddcManagerPasswordComplexity` cmdlet post validation is failing

### ISSUE THREAD

**Issue by sowjuec** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#23]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

v5.0

### PowerShell Version

Windows Powershell 5.1

### PowerCLI Version

v13.0.0

### Module Version

v1.0.0.1002

### PowerValidatedSolutions Version

v2.2.0

### PowerVCF Version

v2.2.0.1002

### Guest Operating System

Windows Server 2019

### Environment Details

It is a VCF 5.0 SSO domain setup.

### Description

Run the following cmdlet following [the documentation](https://docs.vmware.com/en/VMware-Cloud-Foundation/4.5/vcf-operations/GUID-22C6746A-6703-47E5-B17A-313EC959EC62.html).

`Update-SddcManagerPasswordComplexity -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -rootPass $rootPass -minLength $minLength -minLowercase $minLowercase -minUppercase $minUppercase -minNumerical $minNumerical -minSpecial $minSpecial -minUnique $minUnique -minClass $minClass -maxSequence $maxSequence -history $history -maxRetry $maxRetry`

Once execution is completed, you should get a successful message.

### Error or Debug Output

`Update-SddcManagerPasswordComplexity` : Update Password Complexity Policy on   SDDC Manager (sfo-vcf01.sfo.rainpole.io): **POST_VALIDATION_FAILED**

### Expected Behavior

Update-SddcManagerPasswordComplexity cmdlet execution to be successfull

### Actual Behavior

`Update-SddcManagerPasswordComplexity `: Update Password Complexity Policy on   SDDC Manager (sfo-vcf01.sfo.rainpole.io): **POST_VALIDATION_FAILED**

### Steps to Reproduce

Run the following cmdlet following [the documentation](https://docs.vmware.com/en/VMware-Cloud-Foundation/4.5/vcf-operations/GUID-22C6746A-6703-47E5-B17A-313EC959EC62.html).

**Update-SddcManagerPasswordComplexity** -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -rootPass $rootPass -minLength $minLength -minLowercase $minLowercase -minUppercase $minUppercase -minNumerical $minNumerical -minSpecial $minSpecial -minUnique $minUnique -minClass $minClass -maxSequence $maxSequence -history $history -maxRetry $maxRetry

Once execution is completed, you should get a successful message.

**Comment by GaryJBlake** [comment]
Possible change in Password Complexity configuration within SDDC Manager. We have also seen a change concerning the default password expiration
