### ISSUE TITLE
`Update-NsxtManagerPasswordComplexity` cmdlet does not work for NSX 4.x

### ISSUE THREAD

**Issue by sowjuec** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#38]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

`Update-NsxtManagerPasswordComplexity` cmdlet was not updating the configuration for the corresponding passwordpolicy.
Upon checking, it is learnt that on VCF5.0, direct update of common-password file is not supported instead configuration is to be pushed only using NSX CLI's.
This requires Document change as well.

### Use Case(s)

```powershell
Execute the following cmdlets and check if configurations are changed.

Update-NsxtManagerPasswordComplexity -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain $sddcDomainName -minLength $minLength -minLowercase $minLowercase -minUppercase $minUppercase -minNumerical $minNumerical -minSpecial $minSpecial -minUnique $minUnique -maxRetry $maxRetry

Request-NsxtManagerPasswordComplexity   -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass   -domain $sddcDomainName

```

### Potential Configuration

Now the NSX-T API "**https://\<NSX-T manager\>/api/v1/node/aaa/auth-policy**" itself can be used to read the parameters related to password complexity policy as well. So extending the use of this API, will suffice the need.

**Comment by tenthirtyam** [comment]
Dependency on https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/issues/259.
