### ISSUE TITLE
Some functions under PowerShell Core do not return any result or error

### ISSUE THREAD

**Issue by nzRegularIT** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#59]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

v4.5

### PowerShell Version

PowerShell Core 7.2.8

### PowerCLI Version

13.1.0.21624340

### Module Version

1.1.0.1008

### PowerValidatedSolutions Version

2.3.0.1007

### PowerVCF Version

2.3.0.1004

### Guest Operating System

Windows Server 2019

### Description

Request-EsxiPasswordExpiration exits with no output returned

### Error or Debug Output

No error message is produced

### Expected Behavior

Output should display ESXi Password Expiration details for the given workload domain and cluster

### Actual Behavior

No output is returned

#### Note!
One of the workarounds listed here needs to be in place in order to reproduce: [Issue #61 ](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/issues/61)

```powershell
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Install-Module -Name VMware.PowerCLI -MinimumVersion 13.0.0
Install-Module -Name VMware.vSphere.SsoAdmin -MinimumVersion 1.3.9
Install-Module -Name PowerVCF -MinimumVersion 2.3.0
Install-Module -Name PowerValidatedSolutions -MinimumVersion 2.3.0
Install-Module -Name VMware.CloudFoundation.PasswordManagement
```

Open PowerShell Core 7.2.8
```powershell
Request-EsxiPasswordExpiration -server $sddcManagerFQDN -user $sddcManagerAdminUser -pass $sddcManagerAdminPassword -domain $sddcManagerDomain -cluster $sddcManagerCluster
```

### The following functions are affected
```powershell
Request-SsoPasswordComplexity
Request-SsoAccountLockout
Request-EsxiPasswordExpiration
Request-EsxiPasswordComplexity
Request-EsxiAccountLockout
Update-EsxiPasswordExpiration
```

### The affected command is
```powershell
if (Test-Connection -server $server)
```

Test-Connection has different position 0 parameter names in Windows PowerShell vs PowerShell Core

Reference: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-5.1#-computername

### Windows PowerShell
```powershell
Test-Connection -ComputerName
### or its alias:
Test-Connection -Server
```

### PowerShell Core
```powershell
Test-Connection -TargetName
```

### Alternative command
As -ComputerName and -TargetName are both position 0 parameters, the parameter name can be omitted and the parameter $server placed directly after the command Test-Connection
```powershell
if ( Test-Connection $server )
```

**Comment by tenthirtyam** [comment]
This will be addressed in the next release dependent on `PowerValidatedSolution` https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/pull/280.

**Comment by tenthirtyam** [comment]
To be resolved in [GH-62](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/pull/62). We may publish a patch release - stay tuned.

**Comment by nzRegularIT** [comment]
Just a quick note @tenthirtyam, I have tested by pulling the branch `fix/update-connection-test`, and under PowerShell Core on Linux, the error below is produced. Appears to be when `Request-EsxiPasswordExpiration` calls `Test-VsphereConnection` which has the following line `if (Test-Connection -ComputerName ($server) -Quiet -Count 1)`, due to this: https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/7.0/ping-custom-payload-linux

We run PowerShell Core on Linux systems without root access or the ability to change `setcap`. I realise this gets complicated fast, let me know your thoughts?

### Error
From `PowerValidatedSolutions.psm1` version 2.4.0.1008
```
 Error at Script Line 32146
 Relevant Command: if (Test-Connection -ComputerName ($server) -Quiet -Count 1) {
 Error Message: Unable to send custom ping payload. Run program under privileged user account or grant cap_net_raw capability using setcap(8).
```

### Other sample `Test-Connection` on Linux pscore results:
```
PS ~> Test-Connection -ComputerName <sddc-manager-redacted>
Test-Connection: Unable to send custom ping payload. Run program under privileged user account or grant cap_net_raw capability using setcap(8).

PS ~> Test-Connection -ComputerName <sddc-manager-redacted> -TcpPort 443 -Count 1
Test-Connection: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

PS ~> Test-Connection -ComputerName <sddc-manager-redacted> -Count 1
Test-Connection: Unable to send custom ping payload. Run program under privileged user account or grant cap_net_raw capability using setcap(8).

PS ~> Test-Connection -ComputerName <sddc-manager-redacted> -TcpPort 443
True
```

**Comment by tenthirtyam** [comment]
> Just a quick note @tenthirtyam, I have tested by pulling the branch `fix/update-connection-test`, and under PowerShell Core on Linux, the error below is produced. Appears to be when `Request-EsxiPasswordExpiration` calls `Test-VsphereConnection` which has the following line `if (Test-Connection -ComputerName ($server) -Quiet -Count 1)`, due to this: https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/7.0/ping-custom-payload-linux
> 
> 
> 
> We run PowerShell Core on Linux systems without root access or the ability to change `setcap`. I realise this gets complicated fast, let me know your thoughts?
> 
> 
> 
> ### Error
> 
> From `PowerValidatedSolutions.psm1` version 2.4.0.1008
> 
> ```
> 
>  Error at Script Line 32146
> 
>  Relevant Command: if (Test-Connection -ComputerName ($server) -Quiet -Count 1) {
> 
>  Error Message: Unable to send custom ping payload. Run program under privileged user account or grant cap_net_raw capability using setcap(8).
> 
> ```
> 
> 
> 
> ### Other sample `Test-Connection` on Linux pscore results:
> 
> ```
> 
> PS ~> Test-Connection -ComputerName <sddc-manager-redacted>
> 
> Test-Connection: Unable to send custom ping payload. Run program under privileged user account or grant cap_net_raw capability using setcap(8).
> 
> 
> 
> PS ~> Test-Connection -ComputerName <sddc-manager-redacted> -TcpPort 443 -Count 1
> 
> Test-Connection: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
> 
> 
> 
> PS ~> Test-Connection -ComputerName <sddc-manager-redacted> -Count 1
> 
> Test-Connection: Unable to send custom ping payload. Run program under privileged user account or grant cap_net_raw capability using setcap(8).
> 
> 
> 
> PS ~> Test-Connection -ComputerName <sddc-manager-redacted> -TcpPort 443
> 
> True
> 
> ```

Could you open a separate issue for this portion, please? Thanks!

**Comment by tenthirtyam** [comment]
re: https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/issues/59#issuecomment-1610770432

This issue will be resolved upstream in https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/pull/280 and a subsequent update to the `Test-*Connection` functions. This will use the appropriate function(s) based on the `$PSEdition`.

cc @sowjuec

**Comment by nzRegularIT** [comment]
Looks like you have this covered by
https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/pull/280
?

Cheers,

Aaron

**Comment by tenthirtyam** [comment]
> Looks like you have this covered by [vmware-samples/power-validated-solutions-for-cloud-foundation#280](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/pull/280)

The remaining changes are now staged in https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/pull/284. Feel free to give it a go and review/comment on that pull request.
