### ISSUE TITLE
Using `Set-WsaPasswordPolicy` minimum password length can break SDDC Manager Password Rotation

### ISSUE THREAD

**Issue by nzRegularIT** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#69]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Using `Set-WsaPasswordPolicy` to set a minimum password length of 16 characters causes SDDC Manager password rotation to fail as SDDC Manager creates passwords for Workspace ONE admin account of 15 characters.

### Use Case(s)

Applying a security policy where passwords must be a minimum of 16 characters and using SDDC Manager for password rotation.

### Potential Configuration

Applying a security policy where passwords must be a minimum of 16 characters

### References

VCF documentation states that SDDC Manager passwords are 20 characters minimum: https://docs.vmware.com/en/VMware-Cloud-Foundation/4.5/security-and-compliance-configuration-for-vmware-cloud-foundation/GUID-203512B7-9E19-4075-8473-BE9EDEB75D26.html

Workspace ONE admin account is rotated with a 15 character password.

**Comment by tenthirtyam** [comment]
Although it's not yet documented for the module the intent for the WSA cmdlets are for the standalone WS1A instance used in the VMWare Vakidated Solution for IAM and not for the one deployed by vRealize Suite Lifecycle Manager in "vcf-mode".
