### ISSUE TITLE
Add support for `Request/Update-SddcManagerPasswordExpiration`

### ISSUE THREAD

**Issue by nzRegularIT** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#70]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Most services have a `Request-PasswordExpiration`, `Request-PasswordComplexity` and `Request-AccountLockout`.

SddcManager only has `Request-SddcManagerPasswordComplexity` and `Request-SddcManagerAccountLockout`. It does also have`Publish-SddcManagerPasswordExpiration`.

`Request-SddcManagerPasswordExpiration` and `Update-SddcManagerPasswordExpiration` would be helpful

### Use Case(s)

Being able to update and validate SddcManagerPasswordExpiration.

### Potential Configuration

In the interim, `Get-LocalUserPasswordExpiration` and `Set-LocalUserPasswordExpiration` could be used.

**Comment by sowjuec** [comment]
Hi,

There is a General Function, by name `Request-LocalUserPasswordExpiration`. You can use this as a workaround.
For `Request-SddcManagerPasswordExpiration`, use below, by passing `-product` as 'sddcmanager' and `-vmName` as sddcmanager virtual machine name, the same thing can be achieved.

```powershell
Request-LocalUserPasswordExpiration -server $sddcmanagerfqdn -user $user -pass $pass -domain $domain -product sddcmanager -vmName $sddcmanagervmname -guestUser root -guestPassword $guestPassword -localUser "root"
```

For `Update-SddcManagerPasswordExpiration`, use below, by passing `-vmName` as sddcmanager virtual machine name, the same thing can be achieved.

```powershell
Update-LocalUserPasswordExpiration -server $sddcmanagerfqdn -user $user -pass $pass -domain $domain  -vmName $sddcmanagervmname  -guestUser root -guestPassword $guestPassword -localUser "root"
```

We shall surely consider your enhancement request for having exclusive methods like `Request-SddcManagerPasswordExpiration` and `Update-SddcManagerPasswordExpiration` for SDDC manager password expiry operations.

Regards,
Sowjanya.V

**Comment by tenthirtyam** [comment]
@nzRegularIT - for the `Request-SddcManagerPasswordExpiration` how would something like this be for you?

```powershell
PS F:\VMware.CloudFoundation.PasswordManagement> Request-SddcManagerPasswordExpiration -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re123! -rootPass VMw@re123!

Workload Domain : sfo-m01
System          : sfo-vcf01
User            : root
Min Days        : 0
Max Days        : 90
Warning Days    : 7

Workload Domain : sfo-m01
System          : sfo-vcf01
User            : vcf
Min Days        : 0
Max Days        : 90
Warning Days    : 7

Workload Domain : sfo-m01
System          : sfo-vcf01
User            : backup
Min Days        : 0
Max Days        : 365
Warning Days    : 7


PS F:\VMware.CloudFoundation.PasswordManagement> Request-SddcManagerPasswordExpiration -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re123! -rootPass VMw@re123! -drift

Workload Domain : sfo-m01
System          : sfo-vcf01
User            : root
Min Days        : 0
Max Days        : 90
Warning Days    : 7

Workload Domain : sfo-m01
System          : sfo-vcf01
User            : vcf
Min Days        : 0
Max Days        : 90
Warning Days    : 7

Workload Domain : sfo-m01
System          : sfo-vcf01
User            : backup
Min Days        : 0
Max Days        : 365 [ 90 ]
Warning Days    : 7
```
