### ISSUE TITLE
`Invoke-PasswordPolicyManager` cmdlet fails to return workload domain vCenter Server (Local User)

### ISSUE THREAD

**Issue by dgr-en** [vmware/powershell-module-for-vmware-cloud-foundation-password-management#90]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5.1

### PowerShell Version

Windows Powershell 5.1

### PowerCLI Version

13.1.0.21624340

### Module Version

1.2.0.1005 

### PowerValidatedSolutions Version

2.5.0.1010 

### PowerVCF Version

2.3.0.1004

### Guest Operating System

Windows Server 2019

### Environment Details

VMware VCF 4.5.1 environment
- 8 Node streched Management Cluster
WLD
- 2 x 4 Node Cluster Edge_Transport
- 1 x 8 Node Cluster Workloads

### Description

If I generate a Password Policy Report for a Workload Domain, the section _"INFO Collecting vCenter Server (Local User) Password Policies for Workload Domain (xxxxxxx)_" fails.

### Error or Debug Output

```powershell
Invoke-PasswordPolicyManager -sddcManagerFqdn $sddcManagerFqdn -sddcManagerUser $sddcManagerUser -sddcManagerPass $sddcManagerPass -sddcRootPass $sddcRootPass -reportPath $reportPath -darkMode -workloadDomain $workloadDomain `

INFO Collecting vCenter Server (Local User) Password Policies for Workload Domain (xxxxxx).
Invoke-VMScript : 8/9/2023 9:31:01 AM   Invoke-VMScript         Could not find VirtualMachine with name 'xxxxxxxx'.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.5.0.1010\PowerValidatedSolutions.psm1:16905 char:19
+ ...   $output = Invoke-VMScript -VM $vmName -ScriptText $scriptCommand -G ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (xxxxxx-vc01:String) [Invoke-VMScript], VimException
    + FullyQualifiedErrorId : Core_ObnSelector_SelectObjectByNameCore_ObjectNotFound,VMware.VimAutomation.ViCore.Cmdlets.Commands.InvokeVmScript
 
Get-LocalPasswordComplexity : 8/9/2023 9:31:01 AM       Invoke-VMScript         Value cannot be found for the mandatory parameter VM
At C:\Program Files\WindowsPowerShell\Modules\VMware.CloudFoundation.PasswordManagement\1.2.0.1005\VMware.CloudFoundation.PasswordManagement.psm1:3251 char:37
+ ...             Get-LocalPasswordComplexity -vmName ($vcfVcenterDetails.f ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-LocalPasswordComplexity
 
Invoke-VMScript : 8/9/2023 9:31:13 AM   Invoke-VMScript         Could not find VirtualMachine with name 'xxxxxxxx'.
At C:\Program Files\WindowsPowerShell\Modules\PowerValidatedSolutions\2.5.0.1010\PowerValidatedSolutions.psm1:17089 char:19
+ ...   $output = Invoke-VMScript -VM $vmName -ScriptText $scriptCommand -G ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (xxxxxx-vc01:String) [Invoke-VMScript], VimException
    + FullyQualifiedErrorId : Core_ObnSelector_SelectObjectByNameCore_ObjectNotFound,VMware.VimAutomation.ViCore.Cmdlets.Commands.InvokeVmScript
 
Get-LocalAccountLockout : 8/9/2023 9:31:13 AM   Invoke-VMScript         Value cannot be found for the mandatory parameter VM
At C:\Program Files\WindowsPowerShell\Modules\VMware.CloudFoundation.PasswordManagement\1.2.0.1005\VMware.CloudFoundation.PasswordManagement.psm1:3360 char:37
+ ...             Get-LocalAccountLockout -vmName ($vcfVcenterDetails.fqdn. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-LocalAccountLockout

 [08-09-2023_09:31:13] INFO Collecting NSX Manager Password Policies for Workload Domain (xxxxxxxx).
```

### Expected Behavior

vCenter Server (Local User) Password Policies for Workload Domain is included in the Report

### Actual Behavior

Section **vCenter Server (Local User)** is empty.

### Steps to Reproduce

Create a Report with:

```powershell
Invoke-PasswordPolicyManager -sddcManagerFqdn $sddcManagerFqdn -sddcManagerUser $sddcManagerUser -sddcManagerPass $sddcManagerPass -sddcRootPass $sddcRootPass -reportPath $reportPath -darkMode -workloadDomain $workloadDomain
```

... for a Workload Domain, **not** Management Domain.

### Screenshots

![image](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/141398016/e0e7114c-0415-4b01-b9e2-865d91e0fd37)

**Comment by tenthirtyam** [comment]
Based on the error messages, it appears that this is a result of a cmdlet in `PowerValidatedSolutions` not finding the virtual machine with the expected name.

```powershell
Invoke-VMScript         Could not find VirtualMachine with name 'xxxxxxxx'.
```

Therefore, this fails since no value is passed.

```powershell
Invoke-VMScript         Value cannot be found for the mandatory parameter VM
```

Can you confirm that the name of the vCenter Server **VM** is the first part of the FQDN? For example:

- FQDN: sfo-w01-vc01.sfo.rainpole.io
- VM Name: sfo-w01-vc01

**Comment by tenthirtyam** [comment]
As you can see in this test against a workload domain, no error was returned:

```powershell
PS F:\VMware.CloudFoundation.PasswordManagement> Invoke-PasswordPolicyManager -sddcManagerFqdn sfo-vcf01.sfo.rainpole.io -sddcManagerUser administrator@vsphere.local -sddcManagerPass VMw@re123! -sddcRootPass VMw@re123! -reportPath F:\Reporting -darkMode -workloadDomain sfo-w01

 [08-10-2023_10:33:22] INFO Starting the Process of Generating Password Policy Manager Report for Workload Domain (sfo-w01).
 [08-10-2023_10:33:22] INFO Setting up the log file to path F:\Reporting\logs\Invoke-PasswordPolicyManager-08-10-2023_10_33_22.log.
 [08-10-2023_10:33:22] INFO Setting up report folder and report F:\Reporting\PasswordPolicyManager\08-10-2023_10_33_22-passwordPolicyManager-sfo-w01.htm.
 [08-10-2023_10:33:22] INFO Collecting SDDC Manager Password Policies for Workload Domain (sfo-w01).
 [08-10-2023_10:33:25] INFO Collecting vCenter Single Sign-On Password Policies for Workload Domain (sfo-w01).
 [08-10-2023_10:33:35] INFO Collecting vCenter Server Password Expiration Policy for Workload Domain (sfo-w01).
 [08-10-2023_10:33:38] INFO Collecting vCenter Server (Local User) Password Policies for Workload Domain (sfo-w01).
 [08-10-2023_10:34:08] INFO Collecting NSX Manager Password Policies for Workload Domain (sfo-w01).
 [08-10-2023_10:34:37] INFO Collecting NSX Edge Password Policies for Workload Domain (sfo-w01).
 [08-10-2023_10:35:06] INFO Collecting ESXi Password Policies for Workload Domain (sfo-w01).
 [08-10-2023_10:35:28] INFO Generating the Final Report and Saving to (F:\Reporting\PasswordPolicyManager\08-10-2023_10_33_22-passwordPolicyManager-sfo-w01.htm).
```

<img width="1794" alt="image" src="https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/assets/7771363/7a400bb3-a4c8-42d7-acf9-07a40ffd6edd">

**Comment by tenthirtyam** [comment]
Can you please update to the following and retest:
- `PowerValidatedSolutions` v2.6.0
- `VMware.CloudFoundation.PasswordManagement` v1.3.0

Please post the command and results to a Gist and redact the FQDN, password, and VM name with a sample that represents the context for the environment instead of `xxxxxxx` Please redact anything sensitive.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
> Can you please update to the following and retest:
> 
> * `PowerValidatedSolutions` v2.6.0
> * `VMware.CloudFoundation.PasswordManagement` v1.3.0
> 
> Please post the command and results to a Gist and redact the FQDN, password, and VM name with a sample that represents the context for the environment instead of `xxxxxxx` Please redact anything sensitive.
> 
> **Ryan Johnson** Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

Closing Issue: Unable to reproduce and no response from the OP.
